-- Email link signing secret storage (key-value settings). The secret itself is
-- generated by the app on first digest send, never shipped here. Idempotent;
-- never drops user data. Never edit older migrations.
CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
